# Generated by Django 4.2.22 on 2025-09-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0103_fileasset_asset_entity_type_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe subscription ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='subscription_cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='Whether subscription will cancel at period end'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='subscription_current_period_end',
            field=models.DateTimeField(blank=True, help_text='Current subscription period end', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='subscription_current_period_start',
            field=models.DateTimeField(blank=True, help_text='Current subscription period start', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='subscription_price_id',
            field=models.CharField(blank=True, help_text='Stripe price ID for current subscription', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='subscription_status',
            field=models.CharField(default='free', help_text='Current subscription status', max_length=50),
        ),
    ]
